annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.0.0
dependencies:
  - name: common
    repository: https://openchart.choerodon.com.cn/choerodon/c7n
    version: 1.x.x
description: Asgard of Choerodon.
engine: gotpl
home: https://github.com/open-hand/choerodon-asgard/tree/master/chart/choerodon-asgard
icon: https://ui-avatars.com/api/?name=choerodon-asgard
keywords:
  - choerodon
  - asgard
maintainers:
  - email: zhuchiyu@vip.hand-china.com
    name: choerodon
    url: https://choerodon.io
name: choerodon-asgard
sources:
  - https://github.com/open-hand/choerodon-asgard
  - https://gitee.com/open-hand/choerodon-asgard
version: 2.0.0
